spring.application.name=loregard-site

spring.datasource.url=jdbc:postgresql://localhost:5434/loregard_sao_world
spring.datasource.username=loregard_sao_world
spring.datasource.password=Asuna585

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring:
thymeleaf:
prefix: classpath:/templates/
suffix: .html
cache: false